### ISSUE TITLE
Error when loading dataset

### ISSUE THREAD

**Issue by CVAnonymous** [predictive-analytics-lab/nifr#190]
```
  File "run_simple_baselines.py", line 271, in <module>
    main()
  File "run_simple_baselines.py", line 267, in main
    run_baseline(args=args)
  File "run_simple_baselines.py", line 151, in run_baseline
    datasets = load_dataset(args)
  File "/project/nifr/nifr/data/data_loading.py", line 135, in load_dataset
    unbiased_data = CelebA(
  File "/project/nifr/nifr/data/celeba.py", line 162, in __init__
    self.download()
  File "/project/nifr/nifr/data/celeba.py", line 274, in download
    download_file_from_google_drive(
  File "/usr/local/lib/python3.8/dist-packages/torchvision/datasets/utils.py", line 232, in download_file_from_google_drive
    raise RuntimeError(msg)
RuntimeError: The daily quota of the file img_align_celeba.zip is exceeded and it can't be downloaded. This is a limitation of Google Drive and can only be overcome by trying again later.
```

I think there is an error regarding dataset on google drive.
Can you please help me here?

Thanks

**Comment by olliethomas** [comment]
Hi, thanks for checking out our repo. 
This is a known 'problem' with torchvision datasets that are hosted on google drive, if you do a google search you'll see that this is a pretty common. There are only a certain number of downloads of the dataset allowed per hour (I think it's per hour anyway) across all users, and once that's exceeded, you have to wait and try again later. 

There are 2 options to proceed if you are under some time pressure: 
1) If you already have celeba locally, make sure that you use the `--root` flag to point to the dir where the data is, this will skip trying to download the data. 
2) Look for mirrors of the dataset and download from there, then use then proceed as option 1.

I hope that makes sense, Oliver

**Comment by CVAnonymous** [comment]
Oh, Thanks for the kind reply.
I get it. Indeed, I actually thought about 1st option but worried about the originality of the dataset. 

Is it okay with [kaggle](https://www.kaggle.com/jessicali9530/celeba-dataset/version/2) ?

When I download this dataset and run the experiments, it returns false for check_md5.

If not, can you provide the link for downloading the data?

**Comment by CVAnonymous** [comment]
Thanks for the kind reply.
I solved the issue with the first option you suggested. lol
