### ISSUE TITLE
Problem about code running

### ISSUE THREAD

**Issue by scutfrank** [predictive-analytics-lab/nifr#191]
Hello the authors ,
when I follow the step Running the code ,run the code :
start_inn.py --dataset celeba --levels 3 --level-depth 32 --glow True --reshape-method squeeze --autoencode False --input-noise True --quant-level 5 --use-wandb True --factor-splits 0=0.5 1=0.5 --train-on-recon False --recon-detach False --batch-size 32 --nll-weight 1 --pred-s-weight 1e-2 --zs-frac 0.001 --coupling-channels 512 --super-val True --super-val-freq 10 --val-freq 1 --task-mixing 0.5 --gpu 0 --num-discs 10 --disc-channels 512 --data-split-seed 42 --epochs 30
I got 
**bash: start_inn.py: command not found**
I have no idea with it , please help to look at it if you are free ,thanks ! @thomkeh

**Comment by thomkeh** [comment]
You should put `python` in front of the command. I will update the README so that it shows the full command.

**Comment by scutfrank** [comment]
> You should put `python` in front of the command. I will update the README so that it shows the full command.

@thomkeh 
I have add python in front of the command ,then another error happened：
Traceback (most recent call last):
  File "/root/nifr-master/start_inn.py", line 5, in <module>
    main_inn()
  File "/root/nifr-master/nifr/optimisation/train_inn.py", line 222, in main_inn
    repo = git.Repo(search_parent_directories=True)
  File "/root/.local/lib/python3.9/site-packages/git/repo/base.py", line 282, in __init__
    self.working_dir: Optional[PathLike] = self._working_tree_dir or self.common_dir
  File "/root/.local/lib/python3.9/site-packages/git/repo/base.py", line 363, in common_dir
    raise InvalidGitRepositoryError()
git.exc.InvalidGitRepositoryError

**Comment by thomkeh** [comment]
Sorry about that. The code assumed that it was run inside a git repository. I've changed it now such that this isn't required anymore: https://github.com/wearepal/nifr/commit/ca7044c1e9b41af7108357ec98c6512f17eeb463

**Comment by thomkeh** [comment]
I replaced `--epochs 30` with `--iters 76000` in the command: https://github.com/wearepal/nifr/commit/6a513348280fe4e8d0607ad5663b0c8145898ab8 That should work now.

I can't help you with the CUDA error. It depends on how you installed pytorch.

I'm guessing the "403 Forbidden" error is from trying to download the dataset. The dataset is downloaded here:

https://github.com/wearepal/nifr/blob/6a513348280fe4e8d0607ad5663b0c8145898ab8/nifr/data/celeba.py#L273-L276

By default it's downloaded to `./data/celeba` but you can change the location with the `--root` flag. For example, with `--root ../my_data`, the data is expected to be in `../my_data/celeba/`.

**Comment by scutfrank** [comment]
> I replaced `--epochs 30` with `--iters 76000` in the command: [6a51334](https://github.com/wearepal/nifr/commit/6a513348280fe4e8d0607ad5663b0c8145898ab8) That should work now.
> 
> I can't help you with the CUDA error. It depends on how you installed pytorch.
> 
> I'm guessing the "403 Forbidden" error is from trying to download the dataset. The dataset is downloaded here:
> 
> https://github.com/wearepal/nifr/blob/6a513348280fe4e8d0607ad5663b0c8145898ab8/nifr/data/celeba.py#L273-L276
> 
> By default it's downloaded to `./data/celeba` but you can change the location with the `--root` flag. For example, with `--root ../my_data`, the data is expected to be in `../my_data/celeba/`.

@thomkeh 
1.I can't help you with the CUDA error. It depends on how you installed pytorch.
For this question,when change the pin_memory=True to False in ./nifr/optimisation/train_inn.py, it will be OK.

2.For "403 Forbidden",
I found the url in ./nifr/data/celeba.py : http://mmlab.ie.cuhk.edu.hk/projects/CelebA.html
what need download and put in the ./data/celeba is 
-img_align_celeba.zip （need to unzip then)
-list_attr_celeba.txt
-list_eval_partition.txt
then it will be OK.

**3.What are the GPU memory requirements？（16G memory for GPU is OK?）**
16G is OK
